### ISSUE TITLE
MQTT TLS Support

### ISSUE THREAD

**Issue by tam481** [davidmpye/Sonoff-Touch-MQTT#1]
Hello, do you have any plans to implement TLS support for MQTT?

Thank you for making your code available for all to enjoy :-)

**Comment by davidmpye** [comment]
Hi,
You're very welcome!

TLS - That would be down to the underlying library, in my case PubSubClient, adding support.
 
Alternatively, it looks like it would be very easy to use the Adafruit MQTT library which supports TLS instead - as per here:

https://io.adafruit.com/blog/security/2016/07/05/adafruit-io-security-esp8266/

Cheers

David
