### ISSUE TITLE
unsigned long lastMQTTCheck is declared in wrong place

### ISSUE THREAD

**Issue by cayco** [davidmpye/Sonoff-Touch-MQTT#2]
While compiling with platformio I got errors that unsigned long lastMQTTCheck is not declared in this scope (setup()).

When moved from line 160:

unsigned long lastMQTTCheck = 0;

to for line 48 in main.cpp it compiles correctly.

**Comment by davidmpye** [comment]
Good spot - I have updated the branch.  Thanks!
