### ISSUE TITLE
WiFi connection does not work

### ISSUE THREAD

**Issue by cayco** [davidmpye/Sonoff-Touch-MQTT#3]
I successfully uploaded configured code to the switch however it seems that WiFi connection is not working. 

Serial debug says:

```Init

Connecting to ABW-51n
WiFi not connected...
Enabling switch interrupt
Establishing MQTT connection: %
```

and then screen quits. Strangely on my router I have new device in DHCP logs with new IP assigned which seems that the switch is getting the IP but fails to recognize it. 

Printing `Serial.println(WiFi.localIP());` shows `0.0.0.0` on the console. Setting IP statically gets me nowhere. 

I'm using newest platformio and I installed necessary libraries by running: `platformio lib install 555`.

Any idea how to get any further with this?

**Comment by davidmpye** [comment]
Hi,

Bizarrely, I have had this happen once or twice, and for whatever reason,
rebooting the router seemed to fix it.

I have no idea why that should have been necessary!

Could you give that a go?

Cheers

David

**Comment by cayco** [comment]
I have just noticed - it connects but after a while (5s or so). After I reconnect to the serial I can see the IP being printed. I need to play with it some more to figure out what is going on...

**Comment by cayco** [comment]
After debugging on MQTT server I found out that the previous messages (not connected) were not entirely true. It connects now and seems to receive messages. 

This issue can be closed.

**Comment by davidmpye** [comment]
I think it's just that it hasn't connected the first time round but sorts
itself out a bit later on.

Can see how the debug output is a bit misleading.  Will see if I can
improve it!

Glad it is working!
David

**Comment by davidmpye** [comment]
Right, I've improved the debug code so you will get wifi data printed after
the connection has succeeded, so hopefully IP debug will be useful this
time!
