### ISSUE TITLE
I had to use a different board configuration to get a successful flash.

### ISSUE THREAD

**Issue by jfoxcelina** [davidmpye/Sonoff-Touch-MQTT#5]
I am using the Arduino IDE v 1.8.0 on Ubuntu 16.04.
I tried multiple times to flash with the board setup as 'Generic ESP8266' as documented in the wiki.
The upload would complete, but nothing would happen. No serial connection, nothing.
Finally I switch the board configuration to 'Generic ESP8285'. I set Flash Size to 1M, 64K SPIFFS per the wiki. The upload completed and the board connected to my WLAN and MQTT broker.

**Comment by davidmpye** [comment]
Interesting - I'm not sure why, as it isn't an 8285...!

Oh well, pleased it is working, but puzzled as to why!

**Comment by torwag** [comment]
It is an 8285, at least the version I received. Also from the wiki photo about flashing it looks like an 8285. Basically, it looks very much like itead used their own PSF-A85 boards, which sounds logical to me.
