### ISSUE TITLE
Short and long press

### ISSUE THREAD

**Issue by gajotnt** [davidmpye/Sonoff-Touch-MQTT#6]
Hello there, new to this world, just bought some Sonoff devices (Sonoff Touch and Sonoff Basic).
Well my question is, can I configure the touch to do two diferent things? This FW states that you can configure short press and long press, so what I wanted to do in one of my rooms is, short press the Touch and the light turns on and off, and long press would do the same but also change the state of a sonoff basic that has the TV, and all my entertainment related equipment connected to it.

http://i63.tinypic.com/xokx83.jpg

**Comment by davidmpye** [comment]
Hi!

Short answer - yes, you can.

So, you can use the firmware example I provided and populate:

void shortPress() and void longPress()
 I personally would do that by having a MQTT server running on a rasperry
Pi or similar, and have the entertainment sonoff subscribe to a control
topic (as it will do by default anyway), and have the Touch longPress
publish a 'toggle' or similar message to that topic.

David

**Comment by gajotnt** [comment]
Thanks for the reply David. Looking foward to using your FW in my sonoff touch devices :D

**Comment by gajotnt** [comment]
Looking at the code one would have to change this part
```
void longPress() {
  desiredRelayState = !desiredRelayState; //Toggle relay state.

```
To something like this?

```
void longPress() {
Serial.println("changestate");
     client.publish("touch/longpress", "changestate");
}
```
And have the other sonoff read the publish from the touch

**Comment by davidmpye** [comment]
Yep, that's it.

Leave the existing relay state toggle line if you want the toggle to happen
still.


David

**Comment by vladosam** [comment]
Gajotnt, have you solved longpress? Can you share your sketch? Thanks.

**Comment by davidmpye** [comment]
Hmm,

What's wrong with long press?

David

**Comment by vladosam** [comment]
I wanted to publish on mqtt long status topic. I solved it in the mean time. Sorry to bothering you.
