### ISSUE TITLE
How to update firmware via OTA

### ISSUE THREAD

**Issue by Olivierr92500** [davidmpye/Sonoff-Touch-MQTT#8]
Hello,

First of all, thank you for this alternate firmware that wroks really great. I compiled it uploaded and configured with my OpenHab home automation through the MQTT gateway.

I have one question before installing my sonoff into the wall. How can you perform OTA modifications (I am using PlatformIO Environment.

Thanks and kind regards.

Olivier

**Comment by davidmpye** [comment]
Hi, 

Have a look at:

http://docs.platformio.org/en/latest/platforms/espressif8266.html

Basically, 2 things to do:

One, edit platformio.ini and add a line like:

upload_flags = --auth=UPDATE_PW

under the heading of [env:esp8285].

(where UPDATE_PW is your firmware-expected password).

Then, from a platformio terminal, do:

platformio run --target upload --upload-port=IP_ADDRESS

and it should then work!

Bear in mind that unless you comment out the upload_flags line with a # at the beginning of the line, local uploads will fail, but without any useful error message as to why (error 255 usually...!)

David

**Comment by Olivierr92500** [comment]
Thanks a lot David for your quick answer. I will give it a try.

**Comment by davidmpye** [comment]
You're welcome!

Good luck!
